server:
  #debug or release
  Ip: "localhost"
  RunMode: debug
  HttpPort: 8088
  ReadTimeout: 60
  WriteTimeout: 60

logging:
  LogSavePath: "runtime/logs/"
  LogSaveName: "log"
  LogFileExt: "log"
  TimeFormat: "2006-01-02"

jwt:
  JwtSecret: 7234
  Expiration: 3

reCAPTCHA:
  Secret: "6LeEc74pAAAAAKRy3AmMEyoPdbENOsdNwhmck90W"

email:
  Host: "smtp.qq.com"
  Port: "25"
  Username: "481802114@qq.com"
  Password: "wcscfgwsetonbgfi"
  nickname: "微博舆情分析"

mysql:
  Type: mysql
  User: root
  Password: root
  Host: 127.0.0.1:3306
  Name: wb

redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: 0
  poolSize: 30
  minIdleConn: 30
